### ISSUE TITLE
Cannot start apiserver as pod

### ISSUE THREAD

**Issue by aknuds1** [coreos/kubernetes#12]
Using CoreOS alpha (962.0.0), I am unable to start apiserver as a pod, as described in the [CoreOS Kubernetes guide](https://coreos.com/kubernetes/docs/latest/deploy-master.html#set-up-the-kube-apiserver-pod). The problem appears to be that my certificate file can't be opened, although I don't understand why because it's perfectly accessible from the command line. This is how I find the error message:

```
$ sudo cat /var/log/containers/kube-apiserver-*
{"log":"I0227 20:22:58.701844       1 plugins.go:71] No cloud provider specified.\n","stream":"stderr","time":"2016-02-27T20:22:58.702180241Z"}
{"log":"F0227 20:22:58.701965       1 server.go:416] Failure to start kubelet client: open /etc/ssl/etcd/master1-master-client.pem: no such file or directory\n","stream":"stderr","time":"2016-02-27T20:22:58.702229507Z"}
{"log":"I0227 20:28:08.696638       1 plugins.go:71] No cloud provider specified.\n","stream":"stderr","time":"2016-02-27T20:28:08.69710352Z"}
{"log":"F0227 20:28:08.696778       1 server.go:416] Failure to start kubelet client: open /etc/ssl/etcd/master1-master-client.pem: no such file or directory\n","stream":"stderr","time":"2016-02-27T20:28:08.697163308Z"}
```

My pod spec looks as follows:

```
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:v1.1.2
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=127.0.0.1
    - --etcd-config=/etc/kubernetes/etcd.client.conf
    - --allow-privileged=true
    - --service-cluster-ip-range=10.3.0.0/24
    - --secure-port=443
    - --advertise-address=172.31.29.111
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --tls-cert-file=/etc/ssl/etcd/master1-master-client.pem
    - --tls-private-key-file=/etc/ssl/etcd/master1-master-client-key.pem
    - --client-ca-file=/etc/ssl/etcd/ca.pem
    - --kubelet-certificate-authority=/etc/ssl/etcd/ca.pem
    - --kubelet-client-certificate=/etc/ssl/etcd/master1-master-client.pem
    - --kubelet-client-key=/etc/ssl/etcd/master1-master-client-key.pem
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/ssl/etcd
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/kubernetes
      name: conf-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
    path: /etc/ssl/etcd
    name: ssl-certs-kubernetes
  - hostPath:
    path: /etc/kubernetes
    name: conf-kubernetes
  - hostPath:
    path: /usr/share/ca-certificates
    name: ssl-certs-host
```

I have also tried to convert the pod spec to a docker command, and that works perfectly:

`docker run -p 443:443 -v /etc/kubernetes:/etc/kubernetes:ro -v /etc/ssl/etcd:/etc/ssl/etcd:ro gcr.io/google_containers/hyperkube:v1.1.2 /hyperkube apiserver --bind-address=0.0.0.0 --insecure-bind-address=127.0.0.1 --etcd-config=/etc/kubernetes/etcd.client.conf --allow-privileged=true --service-cluster-ip-range=10.3.0.0/24 --secure-port=443 --advertise-address=172.31.29.111 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota --kubelet-certificate-authority=/etc/ssl/etcd/ca.pem --kubelet-client-certificate=/etc/ssl/etcd/master1-master-client.pem --kubelet-client-key=/etc/ssl/etcd/master1-master-client-key.pem --client-ca-file=/etc/ssl/etcd/ca.pem --tls-cert-file=/etc/ssl/etcd/master1-master-client.pem --tls-private-key-file=/etc/ssl/etcd/master1-master-client-key.pem`
